site_description: "FairyGUI是一款超强的UI编辑器，及跨平台开源UI解决方案，制作效率直接提升 50%！，支持Unity、Starling、Egret、LayaAir、Haxe、Pixi、LibGDX等引擎"
site_keywords: "FairyGUI,FGUI,UI编辑器,H5编辑器"
site_index_description: "超强UI编辑器，跨平台开源UI解决方案"
root_domain: github.com
fairygui_version: 3.0
